// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppvgvyiebeqhazqtkgfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdmd2eWllYmVxaGF6cXRrZ2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzY0MTMsImV4cCI6MjA3MzQxMjQxM30.020-AliJfrttqREwOhokRdK0awXO7XFDcD91m4qz6I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});